#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1
PROG=/usr/libexec/istoreos-sms/ensure-storage.sh

start_service() {
	[ "$(uci -q get istoreos_sms.main.auto_repair 2>/dev/null)" = '1' ] || return 0
	[ -x "$PROG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger 'istoreos_sms'
}
